accounts/urls.py
# from django.urls import path, re_path
from accounts import views
from django.conf.urls import url


app_name='accounts'

urlpatterns=[
	url(r'^$',views.IndexTemplateView.as_view(), name = 'index'),
	url(r'^signup/$',views.signup, name = 'signup'),
	url(r'^detail/(?P<pk>\d+)/$',views.ProfileDetailView.as_view(), name = 'profile_detail'),
	url(r'^update/(?P<pk>\d+)/$',views.update_profile, name = 'profile_update'),
	url(r'^delete/(?P<pk>\d+)/$',views.ProfileDeleteView.as_view(), name = 'profile_delete'),

]

appointments/urls.py
from django.conf.urls import url
from appointments import views


app_name = 'appointments'

urlpatterns = [
    # url(r'^create/$', views.new_appointment,name='appointment_create'),
	url(r'^create/$', views.AppointmentCreateView.as_view(),name='appointment_create'),
 	 	

 	url(r'^list/$', views.AppointmentListView.as_view(),name='appointment_list'),
    url(r'^detail/(?P<pk>\d+)/$', views.AppointmentDetailView.as_view(),name='appointment_detail'),
    url(r'^update/(?P<pk>\d+)/$', views.AppointmentUpdateView.as_view(),name='appointment_update'),
    url(r'^delete/(?P<pk>\d+)/$', views.AppointmentDeleteView.as_view(),name='appointment_delete'),   
]

reservationsystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from reservationsystem import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls'), name='accounts'),
    url(r'^loggedin', views.LoggedInTemplateView.as_view(), name='loggedin'),
 	url(r'^loggedout', views.LoggedOutTemplateView.as_view(), name='loggedout'),
    url(r'^$', views.IndexTemplateView.as_view(), name='index'),
    url(r'^appt/', include('appointments.urls', namespace='appointments')),


    url(r'^change_password/$', auth_views.PasswordChangeView.as_view(), name='password_change'),
    url(r'^change_password_done/$', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name = 'user_login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name = 'user_logout'),

]

appointments/models.py
from django.db import models
from django.shortcuts import reverse
from accounts.models import Profile

class Appointment(models.Model):
	
	# TIMESLOT = (
	# 	(0, '08:00 - 09:00'),
	# 	(1, '09:00 - 10:00'),
	# 	(2, '10:00 - 11:00'),
	# 	(3, '11:00 - 12:00'),
	# 	(4, '12:00 - 13:00'),
	# 	(5, '13:00 - 14:00'),
	# 	(6, '14:00 - 15:00'),
	# 	(7, '15:00 - 16:00'),
	# 	(8, '16:00 - 17:00')
	# 	)
	TIMESLOT = (
		(0, '09:00 - 10:00'),
		(1, '10:00 - 11:00'),
		(2, '11:00 - 12:00'),
		(3, '12:00 - 13:00'),
		(4, '13:00 - 14:00'),
		(5, '14:00 - 15:00'),
		(6, '15:00 - 16:00'),
		(7, '16:00 - 17:00'),
		(8, '17:00 - 18:00'),
		)

	user = models.ForeignKey(Profile, on_delete=models.CASCADE)
	section = models.ForeignKey('Section',null=True, blank=True)
	counter = models.ForeignKey('Counter',null=True, blank=True)
	date = models.DateField(null=True, blank=True)
	timeslot = models.IntegerField(choices=TIMESLOT,null=True, blank=True)
	purpose = models.CharField(max_length = 100,null=True, blank=True)
	document = models.FileField(upload_to='static/css', null=True, blank=True)
	
	def __str__(self):
		return '{} {} {} {} {}'.format(self.user, 
									self.section, 
									self.date,
									self.time,
									self.purpose)

	@property
	def time(self):
		return self.TIMESLOT[self.timeslot][1]

	def get_absolute_url(self):
		return reverse('appointments:appointment_detail', kwargs={'pk':self.pk})

	class Meta:
		unique_together = ('section','counter','date', 'timeslot')

class Counter(models.Model):
	section = models.ForeignKey('Section',null=True, blank=True, on_delete=models.CASCADE)
	name = models.CharField(max_length=100,null=True, blank=True)

	def __str__(self):
		return self.name	

class Section(models.Model):
	section_name = models.CharField(max_length=100,null=True, blank=True)

	def __str__(self):
		return self.section_name

appointments/forms.py
from datetime import date

from django import forms
from datetimewidget.widgets import DateTimeWidget

from appointments.models import Appointment


class AppointmentForm(forms.ModelForm):
    document = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
    
    class Meta:
        model = Appointment
        fields = ('section','counter','date', 'timeslot', 'purpose','document')
        widgets = {
            'date': DateTimeWidget(
                attrs={'id': 'date'}, usel10n=False, bootstrap_version=3,
                options={
                    'minView': 2,  # month view
                    'maxView': 3,  # year view
                    'weekStart': 1,
                    'todayHighlight': True,
                    'format': 'yyyy-mm-dd',
                    'daysOfWeekDisabled': [0, 6],
                    'startDate': date.today().strftime('%Y-%m-%d'),
                }),
        }

    def clean_date(self):
        day = self.cleaned_data['date']

        if day <= date.today():
            raise forms.ValidationError('Date should be upcoming (tomorrow or later)', code='invalid')
        if day.isoweekday() in (0, 6):
            raise forms.ValidationError('Date should be a workday', code='invalid')

        return day

appointments/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from appointments.forms import AppointmentForm
from appointments.models import Appointment, Counter, Section
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin 
from django.core.urlresolvers import reverse_lazy
import datetime
from django.views.generic import (TemplateView, ListView, DetailView,
								CreateView, UpdateView, DeleteView)


# @login_required
# def new_appointment(request):
# 	if request.method == 'POST':
# 		form = AppointmentForm(request.POST, request.FILES)
# 		if form.is_valid():
# 			appointment = form.save(commit=False)
# 			appointment.user = request.user
# 			appointment.save()
# 			return redirect('appointments:appointment_list')
# 	else:
# 		form = AppointmentForm()
# 	return render(request, 'appointments/appointment_form.html', {'form': form})

class AppointmentListView(LoginRequiredMixin, ListView):
	model = Appointment

	def get_queryset(self):
		user = self.request.user
		queryset = Appointment.objects.filter(user=user)
		return queryset


class AppointmentDetailView(LoginRequiredMixin, DetailView):
	model = Appointment

	def get_queryset(self):
		user = self.request.user
		queryset = Appointment.objects.filter(user=user)
		return queryset

class AppointmentCreateView(LoginRequiredMixin, CreateView):
	model = Appointment
	form_class = AppointmentForm
	success_url = reverse_lazy('appointments:appointment_list')

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super(AppointmentCreateView, self).form_valid(form)

class AppointmentUpdateView(LoginRequiredMixin, UpdateView):
	model = Appointment
	form_class = AppointmentForm

class AppointmentDeleteView(LoginRequiredMixin, DeleteView):
	model = Appointment
	success_url = reverse_lazy('appointments:appointment_list')

appointments/templates/appointments/appointment_confirm_delete.html
{% extends 'base.html' %}
{% block body_block %}
<section id='main' class='appt_delete'>
<h1>delete FORM</h1>
<form method="POST">
	{% csrf_token%}
	{{object}}
	<input class='btn btn-danger' type="submit" name="Submit">
</form>
</section>
{% endblock %}

appointments/templates/appointments/appointment_detail.html
{% extends 'base.html' %}
{% block body_block %}
<section id='main' class='appt_details'>
	<h1>Appointment Details</h1>

	<p><a href="{% url 'accounts:account_detail' pk=user.pk %}">@{{appointment.user}}</a></p>
	<p>Date: {{appointment.date}} 
	<p>Section: {{appointment.section}}</p>
	<p>Counter: {{appointment.counter}}</p>
	<p>Time: {{appointment.time}}</p>
	<p>Reason: {{appointment.purpose}}</p>
	<p>Files: {{appointment.document}}</p>

	<a class='btn btn-primary' href="{% url 'appointments:appointment_update' pk=appointment.pk %}">Update</a>

	<a class='btn btn-danger' href="{% url 'appointments:appointment_delete' pk=appointment.pk %}">Delete</a>

	<a class='btn btn-info' href="{% url 'password_change' %}">Change Password</a>
</section>
{% endblock %}

appointments/templates/appointments/appointment_form.html
{% extends 'appointments/base.html' %}
{% block appointment_form %}
<section id= 'main' class='new_appt'>
<div class="panel panel-default">
    <div class="panel-body">
        <section id="form-wrapper">
        	<h1>new appointment FORM</h1>
            <form enctype="multipart/form-data" method="POST" class="appointment-form">{% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Save</button>
                <button type="reset" class="btn btn-default">Reset</button>
            </form>
        </section>
    </div>
</div>
</section>

{% endblock %}

appointments/templates/appointments/appointment_list.html
{% extends 'base.html' %}
{% block body_block %}
<section id='main' class='appt_list'>
<h1>appointment LIST</h1>

{%if appointment_list %}
{% for appointment in appointment_list %}
	<p><a href="{% url 'appointments:appointment_detail' pk=appointment.pk %}">Hello {{appointment.user}},</p>
	<p> Your appointment with {{appointment.section}} at {{appointment.counter}} is scheduled for {{appointment.date}} at {{appointment.time}}</a></p>
	{% endfor %}
	{% else %}
	<p>No Appointments <a href="{% url 'appointments:appointment_create' %}">Create One</a></p>
	{% endif %}
</section>
{% endblock %}

appointments/templates/appointments/base.html
{% extends 'base.html' %}
{% block body_block %}

{% endblock %}