accounts/api/urls.py
from django.conf.urls import url
from accounts.api import views
app_name = 'api_accounts'
urlpatterns = [
	url(r'(?P<pk>\d+)',views.AccountsRUDAPIView.as_view(),name='api_accounts'),
]

accounts/urls.py
# from django.urls import path, re_path
from accounts import views
from django.conf.urls import url


app_name='accounts'

urlpatterns=[
	url(r'^$',views.IndexTemplateView.as_view(), name = 'index'),
	url(r'^signup/$',views.signup, name = 'signup'),
	url(r'^detail/(?P<pk>\d+)/$',views.ProfileDetailView.as_view(), name = 'profile_detail'),
	url(r'^update/(?P<pk>\d+)/$',views.update_profile, name = 'profile_update'),
	url(r'^delete/(?P<pk>\d+)/$',views.ProfileDeleteView.as_view(), name = 'profile_delete'),

]

reservationsystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from reservationsystem import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls'), name='accounts'),
    url(r'^loggedin', views.LoggedInTemplateView.as_view(), name='loggedin'),
 	url(r'^loggedout', views.LoggedOutTemplateView.as_view(), name='loggedout'),
    url(r'^$', views.IndexTemplateView.as_view(), name='index'),
    url(r'^appt/', include('appointments.urls', namespace='appointments')),


    url(r'^change_password/$', auth_views.PasswordChangeView.as_view(), name='password_change'),
    url(r'^change_password_done/$', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name = 'user_login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name = 'user_logout'),

]

accounts/api/models.py
from rest_framework import serializers
from accounts.models import Accounts

class AccountsSerializer(serializers.ModelSerializer):
	class Meta():
		model = Accounts

accounts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
from django.shortcuts import reverse

class Profile(AbstractUser):
	ideal_weight = models.IntegerField(default=185)

	def __str__(self):
		return self.email

	def get_absolute_url(self):
		return reverse('accounts:profile_detail', kwargs={'pk':pk})
	

accounts/forms.py
from django import forms
from accounts.models import Profile
from django.contrib.auth.forms import UserCreationForm

class ProfileForm(UserCreationForm):
	class Meta():
		model = Profile
		fields = ['email','password1','password2','ideal_weight']

class ProfileUpdateForm(forms.ModelForm):
	class Meta():
		model = Profile
		fields = ['email','ideal_weight']

accounts/api/views.py
from rest_framework import generics
from accounts.api.models import AccountsSerializer
from accounts.models import Accounts

class AccountsRUDAPIView(generics.RetrieveUpdateDestroyAPIView):
	lookup ='pk'
	serializer_class = AccountsSerializer
	queryset = Accounts.objects.all()

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
# Create your views here.
from django.views.generic import (TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView)
from accounts.models import Profile
from accounts.forms import ProfileForm, ProfileUpdateForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

class IndexTemplateView(TemplateView):
	template_name='accounts/index.html'

def signup(request):
	if request.method == 'POST':
		form = ProfileForm(request.POST)
		if form.is_valid():
			profile = form.save(commit=False)
			profile.username = profile.email
			profile.save()
			return redirect('user_login')
	else:
		form = ProfileForm()
	return render(request, 'accounts/signup.html', {'form': form})

def update_profile(request, pk):
	if request.method == 'POST':
		form = ProfileUpdateForm(request.POST, instance=request.user)
		if form.is_valid():
			profile = form.save(commit=False)
			profile.username = profile.email
			profile.save()
			messages.add_message(request, messages.INFO, 'Success, Profile Updated!')
			return redirect('accounts:profile_detail', pk=pk)
		else:
			return HttpResponse(form.errors)
	else:
		form = ProfileUpdateForm(instance=request.user)
	return render(request, 'accounts/profile_form.html', {'form': form})
class ProfileDetailView(LoginRequiredMixin, DetailView):
	model = Profile

	def get_queryset(self):
		user = self.request.user.pk
		queryset = Profile.objects.filter(pk=user)
		return queryset

class ProfileDeleteView(LoginRequiredMixin, DeleteView):
	model = Profile
	success_url = reverse_lazy('index')

accounts/templates/accounts/base.html
{% extends 'base.html' %}
{% block content %}
<h1>App Base HTML</h1>
{% endblock %}

accounts/templates/accounts/index.html
{% extends 'accounts/base.html' %}
{% block content %}
<h1>accounts HTML</h1>
{% endblock %}

accounts/templates/accounts/profile_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>Login HTML</h1>
<form method="POST">
	{% csrf_token %}
	{{object}}
	<input type="Submit" value="Submit">
</form>
{% endblock %}

accounts/templates/accounts/profile_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>Detail HTML</h1>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% if messages %}
{% for message in messages %}
	<li>{{message}}</li>
	{% endfor %}
{% endif %}

<p>{{profile.username}}</p>
<p>{{profile.email}}</p>
<p>{{profile.ideal_weight}}</p>

<a href="{% url 'accounts:profile_update' pk=user.pk %}">Update</a>

<a href="{% url 'accounts:profile_delete' pk=user.pk %}">Delete</a>

<a href="{% url 'password_change' %}">Change Password</a>
{% endblock %}

accounts/templates/accounts/profile_form.html
{% extends 'base.html' %}
{% block content %}
<h1>Update HTML</h1>
<form method="POST">
	{% csrf_token %}
	{{form.as_p}}
	<input type="Submit" value="Submit">
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
<h1>Signup HTML</h1>
<form method="POST">
	{% csrf_token %}
	{{form.as_p}}
	<input type="Submit" value="Submit">
</form>
{% endblock %}