accounts/urls.py
# from django.urls import path, re_path
from accounts import views
from django.conf.urls import url


app_name='accounts'

urlpatterns=[
	url(r'^$',views.IndexTemplateView.as_view(), name = 'index'),
	url(r'^signup/$',views.signup, name = 'signup'),
	url(r'^detail/(?P<pk>\d+)/$',views.ProfileDetailView.as_view(), name = 'profile_detail'),
	url(r'^update/(?P<pk>\d+)/$',views.update_profile, name = 'profile_update'),
	url(r'^delete/(?P<pk>\d+)/$',views.ProfileDeleteView.as_view(), name = 'profile_delete'),

]

appointments/urls.py
from django.conf.urls import url
from appointments import views


app_name = 'appointments'

urlpatterns = [
    # url(r'^create/$', views.new_appointment,name='appointment_create'),
	url(r'^create/$', views.AppointmentCreateView.as_view(),name='appointment_create'),
 	 	

 	url(r'^list/$', views.AppointmentListView.as_view(),name='appointment_list'),
    url(r'^detail/(?P<pk>\d+)/$', views.AppointmentDetailView.as_view(),name='appointment_detail'),
    url(r'^update/(?P<pk>\d+)/$', views.AppointmentUpdateView.as_view(),name='appointment_update'),
    url(r'^delete/(?P<pk>\d+)/$', views.AppointmentDeleteView.as_view(),name='appointment_delete'),   
]

reservationsystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from reservationsystem import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls'), name='accounts'),
    url(r'^loggedin', views.LoggedInTemplateView.as_view(), name='loggedin'),
 	url(r'^loggedout', views.LoggedOutTemplateView.as_view(), name='loggedout'),
    url(r'^$', views.IndexTemplateView.as_view(), name='index'),
    url(r'^appt/', include('appointments.urls', namespace='appointments')),


    url(r'^change_password/$', auth_views.PasswordChangeView.as_view(), name='password_change'),
    url(r'^change_password_done/$', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name = 'user_login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name = 'user_logout'),

]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <title>Make an appointment</title>

    <script type="text/javascript" src="{% static 'css/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'css/bootstrap.min.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/mysite.css' %}">

</head>
<body>


<header>
	<div id="navigation" class="navbar navbar-inverse navbar-fixed-top default" role="navigation">
  		<div class="container">
    		<nav class='navbar'>
				<span class='open-slide'>
					<a href="#" onclick="openSlideMenu()">
						<svg width='30' height='40'>
							<path d='M0,5 30,5' stroke='#fff' stroke-width='5'/>
							<path d='M0,14 30,14' stroke='#fff' stroke-width='5'/>
							<path d='M0,23 30,23' stroke='#fff' stroke-width='5'/>	
						</svg>
					</a>
				</span>	
			</nav>
			<div class="navigation">
				<div id='side-menu' class='side-nav'>
					<a href="#" class='btn-close' onclick="closeSlideMenu()">&times;</a>
					<li><a href="{% url 'index' %}">Home</a></li>
					<li><a href="{% url 'appointments:appointment_create' %}">New Appt</a></li>
					<li><a href="{% url 'accounts:signup' %}">Signup</a></li>
					<li><a href="{% url 'user_login' %}">Login</a></li>
					{% if user.is_authenticated %}
					<li><a href="{% url 'appointments:appointment_list' %}">My Appointments</a></li>
					<li><a href="{% url 'accounts:profile_detail' pk=user.pk %}">Profile</a></li>
					<li><a href="{% url 'user_logout' %}">Logout</a></li>
					{% endif %}
				</div>
			</div>
  		</div>
	</div>
</header>
<div class='clr'></div>


    {% if form %}
    {{ form.media }}
    {% endif %}
	
	{% block content %}
	{% endblock %}
	{% block body_block %}
	{% endblock %}

    {% block appointment_form %}
    {% endblock %}
<script type="text/javascript">
function openSlideMenu(){
	document.getElementById('side-menu').style.width = '350px';
	document.getElementById('main').style.marginLeft = '350px';
}
function closeSlideMenu(){
	document.getElementById('side-menu').style.width = '0px';
	document.getElementById('main').style.marginLeft = '0px';
}
</script>



</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block body_block %}
<section id='main' class='index'>
<h1>Index HTML</h1>
</section>
{% endblock %}

templates/loggedin.html
{% extends 'base.html' %}
{% block body_block %}
<h1>Logged In HTML</h1>
{% endblock %}

templates/loggedout.html
{% extends 'base.html' %}
{% block body_block %}
<h1>Logged Out HTML</h1>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block content %}
<h1>Login HTML</h1>
<form method="POST">
	{% csrf_token %}
	{{form.as_p}}
	<input type="Submit" value="Submit">
</form>
<a href="{% url 'accounts:signup' %}">SignUp</a>

<a href="{% url 'password_reset' %}">Forgot</a>

{% endblock %}